MVCProjeKampı/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCProjeKampı.Controllers
{
    public class AboutController : Controller
    {
        // GET: About

        AboutManager abm = new AboutManager(new EfAboutDal());
        AboutValidator aboutvalidator = new AboutValidator();
        public ActionResult Index()
        {
            var aboutvalues = abm.GetList();
            return View(aboutvalues);
        }
        [HttpGet]
        public ActionResult AddAbout()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAbout(About p)
        {
            ValidationResult results = new ValidationResult();
            results = aboutvalidator.Validate(p);

            if (results.IsValid)
            {
                if (Request.Files.Count > 0)
                {

                    string fileName = Path.GetFileName(Request.Files[0].FileName);
                    string expansion = Path.GetExtension(Request.Files[0].FileName);

                    string fileName1 = Path.GetFileName(Request.Files[1].FileName);
                    string expansion2 = Path.GetExtension(Request.Files[1].FileName);
                    string path = "/AdminLTE-3.0.4/images/" + fileName + expansion;
                    Request.Files[0].SaveAs(Server.MapPath(path));

                    p.AboutImage1 = "/AdminLTE-3.0.4/images/" + fileName + expansion;
                    p.AboutImage2 = "/AdminLTE-3.0.4/images/" + fileName1 + expansion2;
                    abm.AboutAdd(p);
                    return RedirectToAction("Index");
                }
            }
            else
                {
                    foreach (var item in results.Errors)
                    {
                        ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                       
                    }
                }
               
            return RedirectToAction("Index");
        }

        public PartialViewResult AboutPartial()
        {

            return PartialView();
        }

        public ActionResult DeleteAbout(int id)
        {
            var AboutValue = abm.GetById(id);
            if (AboutValue.AboutStatus == true)
            {
                AboutValue.AboutStatus = false;

            }
            else
            {
                AboutValue.AboutStatus = true;

            }
            abm.AboutDelete(AboutValue);
            return RedirectToAction("Index");

        }


    }
}

MVCProjeKampı/Views/About/AboutPartial.cshtml
@model EntityLayer.Concrete.About
<button class="btn btn-primary" data-toggle="modal" data-target="#Modal1">
    Yeni Hakkımızda Yazı Girişi
</button>

<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Hakkımızda Metin Girişi</h2>
            </div>
            @using (Html.BeginForm("AddAbout", "About", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
        <div class="modal-body">
            <label>Hakkımızda Metin: 1</label>
            @*<input type="text" name="AboutDetails1" class="form-control" />*@
            @Html.TextBoxFor(x => x.AboutDetails1, new { @class = "form-control", required = "required" })
            @Html.ValidationMessageFor(x => x.AboutDetails1)
            <br />
            <label>Hakkımızda Metin: 2</label>
            @*<input type="text" name="AboutDetails2" class="form-control" />*@
            @Html.TextBoxFor(x => x.AboutDetails2, new { @class = "form-control", required = "required" })
            @Html.ValidationMessageFor(x => x.AboutDetails2)
            <br />
            <label>Hakkımızda Görsel: 1</label>
            <br />
            @Html.TextBoxFor(x => x.AboutImage1, new { type = "file", required = "required" })
            @Html.ValidationMessageFor(x => x.AboutImage1)
            <br />
            @*<input type="file" name="AboutImage1" class="form-control" data-val="true" data-val-required="Dosya Boş Geçilemez" />*@

            @*<input type="text" name="AboutImage1" class="form-control" />*@

            <br />
            <label>Hakkımızda Görsel 2</label>
            <br />
            @Html.TextBoxFor(x => x.AboutImage2, new { type = "file", required = "required" })
            @Html.ValidationMessageFor(x => x.AboutImage2)
            @*<input type="file" name="AboutImage2" class="form-control" data-val="true" data-val-required="Dosya Boş Geçilemez" />*@
            @*<input type="text" name="AboutImage2" class="form-control" />*@
             <br />
            <br />
            <button class="btn btn-success">Kaydet</button>
        </div>
          


            }
        </div>
    </div>
</div>

<script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>

MVCProjeKampı/Views/About/Index.cshtml
@using EntityLayer.Concrete
@model List<About>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{ string status = "";}
@{ string statusButton = "";}

<div>
    <div class="row gx-5">
        <div class="col" style="margin-top:15px; margin-bottom:5px;">
            <h2>Hakkımızda Veri Listesi </h2>
        </div>
        <div class="col-7" style="margin-top:15px; margin-bottom:5px; margin-right:15px;">
            <br />
            <br />
            @Html.Action("AboutPartial", "About")
            <br />
            <br />
        </div>
    </div>
</div>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Hakkımda</th>
        <th>Hakkımda Detayı</th>
        <th>Görsel-1</th>
        <th>Görsel-2</th>
        <th>Aktif veya Pasif İşlemi</th>
    </tr>
    @foreach (var item in Model)
    {
        if (item.AboutStatus == true)
        {
            status = "Pasif Yap";
        }
        if (item.AboutStatus == false)
        {
            status = "Aktif Yap";
        }
        if (item.AboutStatus == true)
        {
            statusButton = "btn btn-danger";
        }
        if (item.AboutStatus == false)
        {
            statusButton = "btn btn-warning";
        }
<tr>
    <th>@item.AboutID</th>
    <th>@item.AboutDetails1</th>
    <td>@item.AboutDetails2</td>
    <td>
        <a href="@item.AboutImage1" data-toggle="lightbox">
            <img src="@item.AboutImage1" class="img-circle elevation-2" alt="User Image" width="50" />

        </a>

    </td>
    <td>
        <a href="@item.AboutImage2" data-toggle="lightbox">
            <img src="@item.AboutImage2" class="img-circle elevation-2" alt="User Image" width="50" />

        </a>

    </td>
    <td><a href="/About/DeleteAbout/@item.AboutID" class="@statusButton">@status</a></td>
</tr>
    }
</table>


@*<h2>Hakkımızda Veri Listesi</h2>
    <table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>Hakkımda Başlığı</th>
            <th>Aktif Yap</th>
            <th>Pasif Yap</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.AboutID</td>
                <td>Başlık</td>
                <td><a href="" class="btn btn-warning">Aktif Yap</a></td>
                <td><a href="" class="btn btn-danger">Pasif Yap</a></td>
            </tr>
        }
    </table>
        @Html.Action("AboutPartial","About")*@